apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-role
  namespace: ingress-nginx
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses", "ingresses", "ingresses/status", "endpointslices"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "nodes", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "watch"]

- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update"]