apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: nginx-ingress
data:
  # Client request body size (default: 1m)
  client-max-body-size: "10m"

  # Customize the buffer size for large headers
  large-client-header-buffers: "4 32k"

  # Timeouts for various stages of a request
  proxy-connect-timeout: "30s"
  proxy-read-timeout: "30s"
  proxy-send-timeout: "30s"

  # Enable access logs
  enable-access-log: "true"

  # Increase the number of connections
  worker-connections: "1024"

  # Limit the number of keep-alive connections to upstream servers
  keep-alive: "75"

  # # Configure HTTP/2 support
  # http2-max-field-size: "16k"
  # http2-max-header-size: "32k"

  # Set buffer sizes for Nginx buffers
  proxy-buffer-size: "8k"
  proxy-buffers: "4 16k"
  proxy-busy-buffers-size: "24k"

  # Enable Gzip compression
  use-gzip: "true"
  gzip-level: "5"
  gzip-min-length: "256"
  gzip-proxies: "any"
  gzip-types: "application/json application/javascript text/css text/plain application/xml"

  # Customize the client request timeout
  client-body-timeout: "30s"
  client-header-timeout: "30s"

  # # Customize log format (optional)
  # log-format-upstream: |
  #   '$proxy_protocol_addr - [$time_local] "$request" '
  #   '$status $body_bytes_sent "$http_referer" '
  #   '"$http_user_agent" "$request_length" "$request_time"'
