apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ezpzos
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: "/mnt/data"
