apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: ezpzos  # Specify the namespace where you want to create the secret
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEOHpDQ0F0dWdBd0lCQWdJVUZkbjJzNnRZ
TFBzd2VhbDZkd3BQYW9SZitNRXdEUVlKS29aSWh2Y05BUUVMDQpCUUF3Z1lneEN6QUpCZ05WQkFZ
VEFtRjFNUXd3Q2dZRFZRUUlEQU4yYVdNeEREQUtCZ05WQkFjTUEyMWxiREVODQpNQXNHQTFVRUNn
d0VaWHB3ZWpFUE1BMEdBMVVFQ3d3R1pHVjJiM0J6TVJjd0ZRWURWUVFEREE1bGEzTXVaWHB3DQpl
bTl6TG1OdmJURWtNQ0lHQ1NxR1NJYjNEUUVKQVJZVlkyaHlhWE5tWVc1bk1URkFaMjFoYVd3dVky
OXRNQjRYDQpEVEkwTURreU5ERXdNalV5TWxvWERUSTFNRGt5TkRFd01qVXlNbG93Z1lneEN6QUpC
Z05WQkFZVEFtRjFNUXd3DQpDZ1lEVlFRSURBTjJhV014RERBS0JnTlZCQWNNQTIxbGJERU5NQXNH
QTFVRUNnd0VaWHB3ZWpFUE1BMEdBMVVFDQpDd3dHWkdWMmIzQnpNUmN3RlFZRFZRUUREQTVsYTNN
dVpYcHdlbTl6TG1OdmJURWtNQ0lHQ1NxR1NJYjNEUUVKDQpBUllWWTJoeWFYTm1ZVzVuTVRGQVoy
MWhhV3d1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBDQpNSUlCQ2dLQ0FRRUFp
cnljSzIwY3BVRFh0eU1oMi9HZWhsVG9Ncm9jTmdXb3QrbHlHMk14dC94OFpHWDFjSEMvDQpEQW83
YjFWYmc0ZkpVUUlWQ252TjJ5ZENPRjREYzVPNTJDOUVjTllOQ1Y0U2RWdjNWUWtyS2xpU0l5bVpH
cEZsDQp6QlNUR1hseWtJOEpUaytPS0Z0eHZ2Y0pjRTdHNFlKQldiZGozaUdJUWVqMHhIVlZ1Mlo2
VnBzSWttYjliWDVvDQpJMHZRU3VoNUlpZElOdzlZd2VoejZwUjc1UU9teUVnY0F0NnJYQndkTUQ4
WW81cDQrdzRVUkxVd2JqN2h2QmlRDQoyc3hQSHdwT1lPRUlZZnEvMTB0ZThpK3dpc1V1enIwY3li
Yy9yL2Q5aVVIUnl5QVR3ZXBrYUI5dFRYUno2K2tDDQpCUzhCZmhLK2hDUkVhaGtWL2F6Z0F3UzdC
NXI0bjZOdW13SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVVZWZNDQpUWnBjVG9TVlpQRC9mNlNz
NC9CV0FSY3dId1lEVlIwakJCZ3dGb0FVVWVmTVRacGNUb1NWWlBEL2Y2U3M0L0JXDQpBUmN3RHdZ
RFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQ0xzRURZYklCQVB3
DQpPYWs4TmtxeGJWbXM0REJvZGFuT3FWQzlzSWVhbGtCdlRROWlWMG14REdvaFBMa3BuWlZZM0lP
VlBtV1BRMGJ6DQo2RCs2b3h3MjZadUpmMjRqeWZzejlBYUR2TlZpVGN0bjRyelo4enlpZUptYlhZ
MWw2ZGE5ZTd0Wk9YMzNBUVViDQp3cUh0NjUyVnVsdHVpM0ZrVFcxVjZJa000MUNScEJ0SG9rRWZJ
LzBMRnR0NXppR2hFbGxUejBMeTlpdWoxQzNKDQpZdkRxY1dWNTVTK2N0MC9mc3NGbnREKzNZdG8r
K2QvLzFETi9KTTl4MENySVJHRWhTaHprZ1AyUG1MTGhqUjE5DQpJL3hqMWo0NU9jcS9kWDZHUnBF
NGFPbFJML2h4bndVLzhFQjJZNCsvd0ZWSEVaKzIyS2l4RWM4TW9sTENHeUJFDQpCUnl0NjdEZjFB
PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVG
QUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUNLdkp3cmJSeWxRTmUzDQpJeUhiOFo2R1ZPZ3l1aHcyQmFp
MzZYSWJZekczL0h4a1pmVndjTDhNQ2p0dlZWdURoOGxSQWhVS2U4M2JKMEk0DQpYZ056azduWUww
UncxZzBKWGhKMVcvZFZDU3NxV0pJaktaa2FrV1hNRkpNWmVYS1Fqd2xPVDQ0b1czRys5d2x3DQpU
c2JoZ2tGWnQyUGVJWWhCNlBURWRWVzdabnBXbXdpU1p2MXRmbWdqUzlCSzZIa2lKMGczRDFqQjZI
UHFsSHZsDQpBNmJJU0J3QzNxdGNIQjB3UHhpam1uajdEaFJFdFRCdVB1RzhHSkRhekU4ZkNrNWc0
UWhoK3IvWFMxN3lMN0NLDQp4UzdPdlJ6SnR6K3Y5MzJKUWRITElCUEI2bVJvSDIxTmRIUHI2UUlG
THdGK0VyNkVKRVJxR1JYOXJPQURCTHNIDQptdmlmbzI2YkFnTUJBQUVDZ2dFQUJQNUJaZGNkK3gw
Q09ialhSbTBkZVdFMnVjaW4rWGlSUlF4dkpNOWxPNWlvDQpCcWNDd3hYdFVsRlBqdWNocHlXR2Nk
YWpQd2JZcWZHa3JEQVRueC9FZVhGSHFjK1NZbGZUR3o3Tm1idjkxNTdSDQoxNlJWVkRiMW9hcVpH
ZTIySmlaZUk5K3doYzNxVldjT0hUWEFuVVZaanZmQ09uMVFSQVNiZHBsd2ZGNFBJVk5mDQpWVUlu
eXhveDRKS1BkdkthTzF6bndwTDQ1YlI3RlYvU3FrMWVtRUlmMTFyaHM4SEJ3dVhrQ3Ryck1OeFNE
Q1k1DQpnenBORTkvRVNoMlJQK25ESzA1MWtCZjVHVzNhWDRoaGhnT0dlZ25XL0xjNVpPdklQOHZL
VS8vUVZOVTEyT2lODQpNdnRZZmFaemUwd29QcXRUcFlYMTlrck9vZGgvYmJkYWVvTHVtVjBqb1FL
QmdRREFzY2xSOGs3L1JkVTQ0TzRvDQpSSUxvMW1QMll2QVZ4bGVkTnJJNlR3WkxJVUZidzByNUpq
MFdEYWRVS2JUU3BwQzV6SVpWaDVxelJCVmhKMC9TDQoxTW5CQk4ydkwrZzdLMUI1b1FGQUVHVDR3
TFg1RUtSMm1JdDZrNFBsTFBxTmNtVkVkK29qSDZabFFESHBpYmxuDQpiU1lLOENmWlNCQkVRVEZo
bmMzVnpGd00rd0tCZ1FDNFVNOGlXa1NiemNha2NyVWdvRU1KVlhSUktPN3RMeEdkDQpWeXdMZVRZ
cmxmRWRiWjBtbmNMSTBacS9tZEk5R3lJMXhCSU9MWG03LzlBbFdCSzJUTjNZZ0VESTAxbE9hU0xD
DQptN2xPNEZpb3NOSFFEZlM1anNGMmZMTFJvNFQxQ3liby9aaHdYREdsSHhGbFVKMzhpTDlEN0NW
QlNLbGxoViszDQpvc0pObkNreTRRS0JnRnFMYitqMHJoQWZkVWlyME56VkRKcHlHemlzVnRvMGYv
amN1YlRTYTBla1VielhzSVFRDQpac1hWRnBwaW1wZ2RNb1pMeDVlckI1TlMyNlR5UHZ6M2hmSVA0
a2N1Z0xaRTdTU3A5aGR2WExMU2d1K00xV3J3DQoxU0Y4N1k0anEzd0prL0l2VXJLOGJZaklPR3Zm
am1JK0ZKRXhOZGhRbDJ3ckloUVhmYUFIemYwL0FvR0FZZXRFDQpiOHFuQW1McThqaWljMmZRMVdl
WnVQaFhIcGpQOGRmNjVVbUs5dExjMnJaK002TENkYSt0VjdjZmt5a1VIcDVBDQp2Vmw1ZitBaXM0
UTd4Sy9IZUJxQzBHNC8xc0ZTSHpOZDJrS2p0MUxnMUhobG1DTDRNcnVDd0k3dnRzTXE4OEt1DQpO
cHMwSUxZRnB0NlNZRFJCOEpMSEpBeTNPZUVHZmVldzlFeFBNdUVDZ1lBQi94TXhhbHJqeVc3blRM
SUt6OVpYDQpnaHdFNko3UTlpUWExVHIrdXp4Tkl0SERZNjdJSDVFbUtPR0xJMDVaQUo3bEUzc2Rt
Y1daem5VZ095aVU2QlpMDQp6WFUwNVljQko3d3JOSlNRTnpPNXRtd3lRTThsaGViNk12N0VjUWgz
M2hpa2gyZnN4QVNta0lTa0xCb0FiSm11DQpGTG1rZHdSb2dRTEhib1A0Y3hIVmNRPT0NCi0tLS0t
RU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==
